services:
  php:
    image: php:8.4
    container_name: php-container
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000
    ports:
      - "8000:8000"

